#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root using 'sudo bash'"
  exit
fi

git clone https://git.libre-soc.org/git/nmigen.git
git clone https://git.libre-soc.org/git/c4m-jtag.git
git clone https://git.libre-soc.org/git/nmutil.git
git clone https://git.libre-soc.org/git/openpower-isa.git
git clone https://git.libre-soc.org/git/ieee754fpu.git
git clone https://git.libre-soc.org/git/nmigen-soc.git
git clone https://git.libre-soc.org/git/soc.git

# nmigen
cd nmigen
git checkout -f 24jan2021_ls180 
git tag | xargs git tag -d # very annoying
python3 setup.py develop

# nmigen-soc
cd ../nmigen-soc
git tag | xargs git tag -d # very annoying
python3 setup.py develop

# c4m-jtag
cd ../c4m-jtag
git tag | xargs git tag -d # very annoying
python3 setup.py develop

# nmutil
cd ../nmutil
python3 setup.py develop

# openpower-isa
cd ../openpower-isa
python3 setup.py develop
make svanalysis
make pywriter
make pyfnwriter

# ieee754fpy
cd ../ieee754fpu
git submodule update --init --recursive
python3 setup.py develop

# soc
cd ../soc
make gitupdate
python3 setup.py develop
make mkpinmux

cd ../
chown -R $SUDO_USER .
chgrp -R $SUDO_USER .
echo -e "
\e[1;91mAll Libre-SOC dev dependenices should now be installed.\e[0m
"
