#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root using 'sudo bash'"
  exit
fi

apt-get update -y
apt-get install -y git autoconf make g++ bison flex gperf libreadline6-dev

# change into $SUDO_USER home directory
cd /home/$SUDO_USER
mkdir -p src/iverilog
cd src/iverilog

git clone https://github.com/steveicarus/iverilog.git

cd iverilog
git checkout v11_0
sh autoconf.sh
./configure --prefix=/usr/local/iverilog
make -j$(nproc)
make check
make install

cd /home/$SUDO_USER/src/iverilog
chown -R $SUDO_USER .
chgrp -R $SUDO_USER .

